---
name: readme

on:
  pull_request:
    branches:
      - main

jobs:
  generate:
    name: generate
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: render terraform readme
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          outputfile: README.md
          indention: 3
          git-push: true
          git-commit-message: "terraform-docs: automated action"
